apiVersion: v1
kind: Service
metadata:
  name: my-service  #service name
spec:
  type: NodePort # service type
  selector:
    app: nginx # label of pod
  ports:
    - protocol: TCP
      port: 80  # Host Port
      targetPort: 80 # Container Port
      nodePort: 30007 # Service Port



  
 